Update README.md
Akebi-Group/Akebi-GC pull request #197
Opened 2022-07-01 15:42 UTC by alt3ri

Sorry Paimon, they forgor 💀

2022-07-01 15:44 UTC, lunaticwhat commented
he forgor💀

2022-07-01 15:46 UTC, alt3ri commented
I forgor too 💀

2022-07-02 02:12 UTC, lunaticwhat reviewed
a

2022-07-02 02:12 UTC, lunaticwhat commented on README.md
> +<h2>Press F1 to open the cheat menu first</h2>
`Press F1 to open Akebi GUI` or `Press F1 to open the menu` is enough

2022-07-02 02:15 UTC, lunaticwhat commented on README.md
> +<h2>Press F1 to open the cheat menu first</h2>
oh nvm. I just read the readme again and it shoud be a last step in **Usage** section instead of feature.

2022-07-02 14:52 UTC, CPP-Callow requested changes
Check @lunaticwhat review.

2022-07-03 18:52 UTC, CPP-Callow requested changes

2022-07-03 18:52 UTC, CPP-Callow commented on README.md
> +<h2>Press F1 to open Akebi GUI</h2>
Bruh. Why you didn't move it to correct section?

2022-07-06 23:52 UTC, merged