Addition to #387 PR.
Akebi-Group/Akebi-GC pull request #444
Opened 2022-08-09 16:24 UTC by TerraFaster

• Moved and renamed some feature files.
• Moved some stuff into the Combat Tab.
• Changed features appearance.

2022-08-10 00:58 UTC, CallowBlack requested changes
I can't test it right now, but with statically check, I see several moments with bad design. Like unnecessary groups. Also, I don't know is big sections looks goods or not with current UI solution.
So, I can't approve it right now, and better if someone check it in game, and post here review.
And isn't `CollapsingHeader` make UI too compact.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/combat/AttackEffects.cpp
> +		AttackEffects& AttackEffects = AttackEffects::GetInstance();
Better have difference between type and variable name, and variables should start with lowercase.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/imap/InteractiveMap.cpp
> +		static const FeatureGUIInfo info{ "Interactive Map", "World", true };
No need of any fixes here. Because interactive map is not drawing anything to main cheat menu. Check `InteractiveMap::DrawMain`

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/imap/InteractiveMap.cpp
> +		ImGui::BeginGroupPanel("Interactive Map");
I don't think that it's also needed, because we already in interactive map window.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +        ImGui::BeginGroupPanel("Hotkeys");
Also don't think that it's needed here.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
Why just not use `node` argument in BeginGroupPanel instead?

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
Or if you use `CollapsingHeader` then remove `GroupPanel`

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoDialog.cpp
> +        AutoDialog& AutoDialog = AutoDialog::GetInstance();
Incorrect variable name again.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoLoot.cpp
> +			ImGui::BeginGroupPanel("Auto Loot");
The same, do you need both of them?

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/teleport/OculiTeleport.cpp
> -		static const FeatureGUIInfo info{ "0culi Teleport", "Teleport", true };
It's a trick for sorting. If change to `O` the section move to down.

2022-08-10 00:58 UTC, CallowBlack commented on cheat-library/src/user/cheat/visuals/ProfileChanger.cpp
> +        ImGui::BeginGroupPanel("Custom Profile");
`Custom Profile` in `Custom Profile`?

2022-08-10 00:59 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
Also, you can modify begin group panel collapsed view, add line or something like.

2022-08-10 11:04 UTC, TerraFaster commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +        ImGui::BeginGroupPanel("Hotkeys");
IDK. I think it is more beautiful with Group Panel.
![With Group Panel](https://user-images.githubusercontent.com/49460242/183885992-21044ca8-9013-4ce8-91ae-581612418655.png)
![Without Group Panel](https://user-images.githubusercontent.com/49460242/183886025-6aff1cf7-795d-4a96-ab20-c17ae768ee62.png)

2022-08-10 12:16 UTC, TerraFaster commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
Again, this is more beautiful using CollapsingHeader and GroupPanel together. If we will use only CollapsingHeader it will be a little harder to navigate through.
Yes, we can use `ImGui::Indent()` but it won't be as pretty as using CollapsingHeader and GroupPanel together.

(Example is not with `AutoCook`, but with `CustomProfile` and `FPSUnlock` features)

With CollapsingHeader and GroupPanel:
![With GroupPanel](https://user-images.githubusercontent.com/49460242/183897897-3ab7935c-5a67-427a-aa19-05ad125996b9.png)

With only CollapsingHeader:
![Without GroupPanel](https://user-images.githubusercontent.com/49460242/183898033-c6b1f670-ada9-4b6e-b4d8-11ef1a9c67a2.png)

2022-08-10 12:19 UTC, TerraFaster commented on cheat-library/src/user/cheat/visuals/ProfileChanger.cpp
> +        ImGui::BeginGroupPanel("Custom Profile");
Refer to https://github.com/Akebi-Group/Akebi-GC/pull/444#discussion_r942377230

2022-08-10 12:19 UTC, TerraFaster commented on cheat-library/src/user/cheat/player/AutoLoot.cpp
> +			ImGui::BeginGroupPanel("Auto Loot");
Refer to https://github.com/Akebi-Group/Akebi-GC/pull/444#discussion_r942377230

2022-08-10 15:27 UTC, CallowBlack approved these changes

2022-08-10 15:29 UTC, CallowBlack commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
Yeah, but you can modify a little group panel widget for empty strings, and remove the duplicating name this way.

2022-08-10 15:30 UTC, CallowBlack commented
Seems better now, but I want to ask other people for their opinion, because for me duplicating the name of section. And I still think that for hotkeys, not need the group panel.

2022-08-10 16:12 UTC, Taiga74164 commented on cheat-library/src/user/cheat/player/AutoCook.cpp
> +            ImGui::BeginGroupPanel("Auto Cooking");
I feel like having 2 titles is a bit redundant. If you do like the outlines that ``BeginGroupPanel`` has then maybe use it with ``##``. Will need other's opinion on this.

2022-08-11 06:23 UTC, harlanx commented
Is this dependent on #387 (if it is why not push it on that fork...) or this PR just have the same objective?

2022-08-12 02:00 UTC, TerraFaster commented
> Is this dependent on #387 (if it is why not push it on that fork...) or this PR just have the same objective?

This PR just have the same objective but idea was taken from #387 and implemented in a better way.

2022-08-12 15:09 UTC, Shichiha approved these changes
LGTM!

2022-08-13 06:18 UTC, harlanx commented
Sorry to intrude but can you edit these files and add something like this so it doesn't have to render the blank space in BeginGroupPanel, also I recommend for you to replace "" with hashed ids to prevent any possible id collisions. Thanks.
<details>
<summary>gui-util.cpp</summary>

```diff
	bool BeginGroupPanel(const char* label, bool node, const ImVec2& size)
	{
		ImGuiContext& g = *GImGui;
		ImGuiWindow* window = g.CurrentWindow;
+		std::string labelText = std::string(label).substr(0, std::string(label).find("##"));
		const ImGuiID id = window->GetID(label);
		ImGui::PushID(id);

		...

		auto frameHeight = ImGui::GetFrameHeight();
		ImGui::Dummy(ImVec2(frameHeight * 0.5f, 0.0f)); ImGui::SameLine(0.0f, 0.0f); // Inner group spacing
		ImGui::BeginGroup(); // Inner group

+		if (!labelText.empty()) {
			ImGui::Dummy(ImVec2(frameHeight * 0.5f, 0.0f)); ImGui::SameLine(0.0f, 0.0f); // Name text spacing
-			ImGui::TextUnformatted(label);
+			ImGui::TextUnformatted(labelText.c_str());
+		}

		ImRect leftRect = { ImGui::GetItemRectMin(), ImGui::GetItemRectMax() };
		ImVec2 rightMax = ImVec2(groupPanelPos.x + effectiveSize.x - frameHeight, leftRect.Max.y);
		...
```

</details>

And then on other files for example:
<details>
<summary>AutoLoot.cpp</summary>

```diff
		if (ImGui::CollapsingHeader("Auto Loot"))
		{
-			ImGui::BeginGroupPanel("");
+			ImGui::BeginGroupPanel("##Auto Loot");
			{
```

</details>
<details>
<summary>AutoCook.cpp</summary>

```diff
       if (ImGui::CollapsingHeader("Auto Cooking"))
        {
-            ImGui::BeginGroupPanel("");
+            ImGui::BeginGroupPanel("##Auto Cooking");
            {
```

</details>
<details>
<summary>AutoDialog.cpp</summary>

```diff
        if (ImGui::CollapsingHeader("Auto Dialog"))
        {
-            ImGui::BeginGroupPanel("");
+            ImGui::BeginGroupPanel("##Auto Dialog");
            {
```

</details>

Also revert this back to an if statement so it'll correctly hide the children when collapsed

<details>
<summary>Hotkeys.cpp</summary>

```diff
            for (auto& fields : multiLineSections)
            {
-                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
+                if(ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true))
                {
                    for (auto& field : *fields)
                    {
                        ConfigWidget(*field, nullptr, true);
                    }
                }
                ImGui::EndGroupPanel();
            }
```

</details>

2022-08-13 06:28 UTC, harlanx commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
Also revert this back to an if statement so it'll correctly hide the children when collapsed.

2022-08-13 11:59 UTC, TerraFaster commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
> edit these files and add something like this so it doesn't have to render the blank space in BeginGroupPanel, also I recommend for you to replace "" with hashed ids to prevent any possible id collisions.

Yeah, thanks for the great idea!

2022-08-13 13:07 UTC, harlanx commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
Oops my bad if it got confusing. That request for revert change was only meant for the Hotkeys.cpp

2022-08-13 13:23 UTC, TerraFaster commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
Bruh

2022-08-13 13:30 UTC, TerraFaster commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
It works anyway, so i don't think it needs to be reverted ^_^

2022-08-13 13:44 UTC, harlanx commented on cheat-library/src/user/cheat/misc/Hotkeys.cpp
> +                ImGui::BeginGroupPanel((*fields)[0]->section().c_str(), true);
Oh ok then

2022-09-11 14:31 UTC, closed without merging