Add Quality of Life Features
Akebi-Group/Akebi-GC pull request #554
Opened 2022-08-27 23:54 UTC by EchoesFromBeyond

Add's in Quality of Life Features -> GameSpeed, Destroy Objects, Destroy Chests, Special Destroy HotKey based Destruction of certain objects.

Added Quality of Life Sub-Section of "World" along with multiple features.

1. GameSpeed feature
Add's in a GameSpeed feature that lets you configure a HotKey and a TimeScale, when HotKey is held it speeds up the game by the TimeScale.

The risk with this is mostly within using it in the open world. Menu's should be safe, open world can't be determined. Would recommend against it.

2. Add in Destroy Features
Destroy Objects - This will destroy Ancient Rime and Large / Small Rock Piles upon getting within range of them.

Destroy Chests - This will automatically break the Brambles, Frozen, and Encased in Rock Chests so that you can just loot them as you normally would.

Destroy *Special - This will allow you to set a HotKey and Range. When you press said HotKey and you are within the "Destroy Range" of certain special objects, it will destroy them. Currently this is only for Scarlet Quartz but will be adding other special objects as I get suggestions to it.

**Coming Soon**
Adding in Auto Killing of Animals for Cooking Material Farming. Will be able to do this with the Destroy Key or with the Automatic Mode.

2022-08-27 23:57 UTC, Taiga74164 requested changes

2022-08-27 23:57 UTC, Taiga74164 commented on cheat-library/src/user/cheat/world/QoL.cpp
> +        HookManager::install(app::MoleMole_LCAbilityElement_ReduceModifierDurability, LCAbilityElement_ReduceModifierDurability_Hook);
so 2 Hooks for this function exist?

2022-08-27 23:57 UTC, Taiga74164 commented on cheat-library/src/user/cheat/world/QoL.cpp
> +    static void LCAbilityElement_ReduceModifierDurability_Hook(app::LCAbilityElement* __this, int32_t modifierDurabilityIndex, float reduceDurability, app::Nullable_1_Single_ deltaTime, MethodInfo* m
why dont you just modify AutoDestroy itself

2022-08-28 00:07 UTC, Lunairayz commented
not even 5 minutes have passed since pr opening

already rolled and smoked by taiga <:KEKW:987140202231382056>

2022-08-28 00:32 UTC, closed without merging